### ISSUE TITLE
how to build it?

### ISSUE THREAD

**Issue by huge818** [piskorzj/node-packet-socket#1]

**Comment by huge818** [comment]
i build it error!
win10 x64  vs2015 node6.9.5

**Comment by piskorzj** [comment]
Right now it heavily depends on Linux socket API, so until someone adds windows support, I'm afraid you'll not be able to build it on windows.

I need to add notice about Linux dependency to README.

**Comment by huge818** [comment]
root@ubuntu:~/node-packet-socket# node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@6.10.2 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/root/node-v6.10.2-linux-x64/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/node-packet-socket/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/node-v6.10.2-linux-x64/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/6.10.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.10.2',
gyp info spawn args   '-Dnode_gyp_dir=/root/node-v6.10.2-linux-x64/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/node-packet-socket',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
root@ubuntu:~/node-packet-socket# node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@6.10.2 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/root/node-v6.10.2-linux-x64/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/node-packet-socket/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/node-v6.10.2-linux-x64/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/6.10.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.10.2',
gyp info spawn args   '-Dnode_gyp_dir=/root/node-v6.10.2-linux-x64/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/node-packet-socket',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/root/node-packet-socket/build'
  CXX(target) Release/obj.target/packet_socket_addon/src/wrapper.o
In file included from ../node_modules/nan/nan.h:2316:0,
                 from ../include/wrapper.hh:5,
                 from ../src/wrapper.cc:1:
../node_modules/nan/nan_json.h: In member function ‘Nan::MaybeLocal<v8::Value> Nan::JSON::Parse(v8::Local<v8::String>)’:
../node_modules/nan/nan_json.h:87:52: warning: ‘static v8::Local<v8::Value> v8::JSON::Parse(v8::Local<v8::String>)’ is deprecated (declared at /root/.node-gyp/6.10.2/include/node/v8.h:1681): Use maybe version [-Wdeprecated-declarations]
     return scope.Escape(v8::JSON::Parse(json_string));
                                                    ^
  CXX(target) Release/obj.target/packet_socket_addon/src/socket.o
  CXX(target) Release/obj.target/packet_socket_addon/src/poller.o
  SOLINK_MODULE(target) Release/obj.target/packet_socket_addon.node
  COPY Release/packet_socket_addon.node
  CXX(target) Release/obj.target/test_poller/src/poller.o
  CXX(target) Release/obj.target/test_poller/cc_tests/poller.o
In file included from ../node_modules/nan/nan.h:2316:0,
                 from ../cc_tests/poller.cc:1:
../node_modules/nan/nan_json.h: In member function ‘Nan::MaybeLocal<v8::Value> Nan::JSON::Parse(v8::Local<v8::String>)’:
../node_modules/nan/nan_json.h:87:52: warning: ‘static v8::Local<v8::Value> v8::JSON::Parse(v8::Local<v8::String>)’ is deprecated (declared at /root/.node-gyp/6.10.2/include/node/v8.h:1681): Use maybe version [-Wdeprecated-declarations]
     return scope.Escape(v8::JSON::Parse(json_string));
                                                    ^
  SOLINK_MODULE(target) Release/obj.target/test_poller.node
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libCppUTest.a(libCppUTest_a-MemoryLeakWarningPlugin.o): relocation R_X86_64_32 against `_ZNSt9bad_allocD1Ev' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libCppUTest.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/test_poller.node] Error 1
make: Leaving directory `/root/node-packet-socket/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/node-v6.10.2-linux-x64/lib/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.13.0-32-generic
gyp ERR! command "/root/node-v6.10.2-linux-x64/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/node-packet-socket
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok 
root@ubuntu:~/node-packet-socket#

**Comment by piskorzj** [comment]
Please run:
`npm install-test`
on cloned repo.
