### ISSUE TITLE
Doesn't build on Ubuntu 16.04

### ISSUE THREAD

**Issue by alanmimms** [piskorzj/node-packet-socket#2]
I tried `npm install-test` as you suggested in #1 but it fails. Apparently you must have [cpputest](https://cpputest.github.io/) installed. I installed that using `apt-get install cpputest` which also installs `libcpputest-dev` for development.

This was not sufficient either because Ubuntu ships `libcpputest-dev` as a dynamic binding library or something? Do you have to build a specialized version of `libCppUTest.a` to make this work? The error I got is shown in the sequence below:

```
$ npm install-test

> packet-socket@1.0.1 install /home/alan/node-packet-socket
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/alan/node-packet-socket/build'
  CXX(target) Release/obj.target/packet_socket_addon/src/wrapper.o
  CXX(target) Release/obj.target/packet_socket_addon/src/socket.o
  CXX(target) Release/obj.target/packet_socket_addon/src/poller.o
  SOLINK_MODULE(target) Release/obj.target/packet_socket_addon.node
  COPY Release/packet_socket_addon.node
  CXX(target) Release/obj.target/test_poller/src/poller.o
  CXX(target) Release/obj.target/test_poller/cc_tests/poller.o
  SOLINK_MODULE(target) Release/obj.target/test_poller.node
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libCppUTest.a(lib_libCppUTest_a-CommandLineTestRunner.o): relocation R_X86_64_32S against `_ZTV21CommandLineTestRunner' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libCppUTest.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
test_poller.target.mk:126: recipe for target 'Release/obj.target/test_poller.node' failed
make: *** [Release/obj.target/test_poller.node] Error 1
make: Leaving directory '/home/alan/node-packet-socket/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/alan/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.4.0-79-generic
gyp ERR! command "/home/alan/.nvm/versions/node/v8.1.0/bin/node" "/home/alan/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/alan/node-packet-socket
gyp ERR! node -v v8.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! packet-socket@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the packet-socket@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alan/.npm/_logs/2017-06-08T22_09_59_260Z-debug.log
```

**Comment by piskorzj** [comment]
Indeed I have CppUTest built manually (commit 2cba8d289d2ef07c213353efb1988ef2fb190633, day after v3.8 tag - don't remember why...). I need to check this behavior with cpputest when installed from apt.

In the mean time, can you check if **ld** suggestion is sufficient - to add fPIC flag?, you would need to modify binding.gyp (https://gist.github.com/piskorzj/f044536035a06f3164dda85c886d1f1f).

Also, is installing module through npm working for you?

**Comment by alanmimms** [comment]
I can install the module using `npm install packet-socket` but it won't work without gyp building the native stuff, of course.

I haven't tried forcing `ld` to use `-fPIC` because `-fPIC` is a code generation option for the compiler, not a linker option, no? I'll try it for completeness, but I have always believed this to be true. I'm about 75% done with building libCppUTest from sources with modifications to its `Makefile.am` to get it to build both the static and PIC/shareable versions of the library. I actually got that to build, but now I can't seem to trick node-gyp into letting me build your module with it. I keep getting `dlopen` errors. I'm looking for the reason, but I strongly suspect it is because I built my `libCppUTest` stuff into `/usr/local` rather than into `/usr`. I might just symlink the files there to see if that fixes the problem.

**Comment by alanmimms** [comment]
That was it. I symlinked my built `CppTest` libraries and interface files into `/usr` (from `/usr/local`) and it builds fine now. Testing...

**Comment by alanmimms** [comment]
Tests passed as well. So that was it.

**Comment by alanmimms** [comment]
BTW, you might wish to know I'm doing this using node v8.1.0. That's another difference I can't believe I forgot to mention until now. Oops. :sob:
